export const enum PATHS {
  MAIN = '/',
  REGISTRATION = '/registration',
  LOGIN = '/login',
  CONTACTS = '/contacts',
  ABOUT = '/about',
  VACANCIES = '/vacancies',
  VACANCY_ID = '/vacancies/:id',
  ADD_VACANCY = '/add-vacancy',
  TESTS = '/tests',
  TEST_ID = '/tests/:id',
  ACCOUNT = '/account',
  RESUME = '/resume',
  ADD_RESUME = '/add-resume',
  RESULT = '/result',
  RESULT_ID = '/result/:id',
  ADMIN = '/admin',
  ADD_TEST = '/add-test',
  ADD_QUESTION = '/add-question',
}
