export * from './main';
export * from './registration';
export * from './login';
export * from './Account';
export * from './vacancies';
export * from './vacancy';
export * from './add-vacancy';
export * from './tests-page';
export * from './test-page';
export * from './result';
export * from './add-test';
export * from './add-qestion';
export * from './add-resume';
export * from './resume';
export * from './admin';
export { AppRouter } from './routes';
